"""Added requests table

Revision ID: ab38d5dd79bd
Revises: b7e703199d70
Create Date: 2026-07-20 18:42:57.600197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab38d5dd79bd'
down_revision = 'b7e703199d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('IDRequest', sa.Integer(), nullable=False),
    sa.Column('RequestTitle', sa.Unicode(length=128), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('Place', sa.Unicode(length=64), nullable=True),
    sa.Column('Comment', sa.Unicode(length=1024), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=50), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=50), nullable=True),
    sa.Column('RequestStatusId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RequestStatusId'], ['request_statuses.IDRequestStatus'], ),
    sa.PrimaryKeyConstraint('IDRequest')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
