"""added request statuses table

Revision ID: b7e703199d70
Revises: d60bcdfd07ff
Create Date: 2026-07-09 19:21:02.936842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e703199d70'
down_revision = 'd60bcdfd07ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_statuses',
    sa.Column('IDRequestStatus', sa.Integer(), nullable=False),
    sa.Column('RequestStatusName', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('IDRequestStatus')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_statuses')
    # ### end Alembic commands ###
