"""initial migration

Revision ID: d60bcdfd07ff
Revises: 
Create Date: 2026-06-18 18:39:57.288171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60bcdfd07ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('IDRoles', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('IDRoles')
    )
    op.create_table('users',
    sa.Column('IDUser', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=32), nullable=True),
    sa.Column('FullName', sa.String(length=64), nullable=True),
    sa.Column('Email', sa.String(length=64), nullable=True),
    sa.Column('Password', sa.String(length=255), nullable=True),
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('IsActive', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['RoleId'], ['roles.IDRoles'], ),
    sa.PrimaryKeyConstraint('IDUser')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
